services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: svc_user
      POSTGRES_PASSWORD: svc_password
      POSTGRES_DB: user-session-service
    ports:
      - "5423:5423"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data